### ISSUE TITLE
Unable to enter directory if it contains space in its name

### ISSUE THREAD

**Issue by korry73** [dubyte/dir2opds#10]
Hi, thanks for the great utility, exactly what I was looking for. Unfortunately a small issue prevents me from sharing my books catalog via OPDS: I am unable to enter a directory if it contains a space in its name and 99% ofmy dirs do havea space (first and last name of the author). I get server response code 400.

![image](https://user-images.githubusercontent.com/32910820/120439246-f8ae2e80-c38a-11eb-94b9-79a81792168a.png)
 it is a sample directory. Only НоаХоули works

![image](https://user-images.githubusercontent.com/32910820/120439646-6a867800-c38b-11eb-880c-4581bcee6c62.png)
this happens when I click on any other dir.

![image](https://user-images.githubusercontent.com/32910820/120439471-390dac80-c38b-11eb-972d-8dbefce71131.png)
But I am able to enter НоаХоули and to download its content.

Could you please fix this?

**Comment by korry73** [comment]
When using version 0.0.4, I can enter any folder even those with spaces in the file name, the fix should be easy I hope.

**Comment by korry73** [comment]
It seems to be broken in 0.0.5 already, prior versions work correctly.

**Comment by dubyte** [comment]
Thank you for this report, as you mentioned the fix was simple.
Please check version 0.0.11 and confirm this issue is resolved.

Thanks

**Comment by korry73** [comment]
It works now, thanks a lot!
