### ISSUE TITLE
Can't connect from KOReader on a Kobo

### ISSUE THREAD

**Issue by klundry** [dubyte/dir2opds#14]
This is just what I was looking for but I'm having trouble connecting to it from a Kobo ereader running KOReader. Has anybody tried this and been successful?

I'm launching dir2opds with "dir2opds -dir microsd/ebooks/", then on the kobo I'm entering the ip address and port of the server running dir2opds. When I try to load the opds catalog after that I get Server response status: timeout.

**Comment by dubyte** [comment]
Hi

I don't have access to koreader.

But you can pass -debug parameter to see the calls on the server stdout.

Did you try to connect to that IP and port from another device and works?

Like your phone/PC browser?

Are you using http instead of https?

**Comment by klundry** [comment]
I've tried on two different machines and a phone. I can access it on same machine it's running on by going to localhost:8080 but it can't reach it from any outside machine. Is the default 0.0.0.0 what I want for being able to access it on my network?

**Comment by dubyte** [comment]
Klundry the 0.0.0.0 on dir2opds is the bind address. with that bind address on the same machine, you can access using localhost as you did.

But when you want to access from another machine in the same network you need to access the machine IP.

on Windows, you can use cmd.exe and use the command: ipconfig
on Linux you can use: ip -c a

For example, the IP of my machine is: 192.168.1.101 if I run dir2opds there with the default bind address 0.0.0.0

I could connect to the server using http://localhost:8080 on the same machine.
or http://192.168.1.101:8080 from another machine or phone on the same LAN network.

**Comment by klundry** [comment]
Yes, I know. I am using the ip of the machine that is running dir2opds when I'm trying to access it from a different machine or device but it doesn't work. I was just asking if the default setting of "0.0.0.0" should generally work or if I need it change it.

I'm not sure what else to try. I have a number of other things accessible on my network with no problems.

**Comment by klundry** [comment]
Alright, turned out to be the firewall on the machine running dir2opds not letting port 8080 out. It is working now. I thought I had run something on 8080 before on this machine but I guess not.
