### ISSUE TITLE
HTTP directory traversal vulnerability

### ISSUE THREAD

**Issue by masked-owl** [dubyte/dir2opds#17]
Security issue, server allows directory transversal with a crafted URL.
Example of Vulnerable URL: http://localhost:8100/.%252e/.%252e/.%252e/.%252e/.%252e/.%252e/etc/passwd

**Comment by dubyte** [comment]
Thanks for reporting this I will check this out.

**Comment by dubyte** [comment]
Thank you again; this is fixed now on the new version.
