### ISSUE TITLE
Seeing .calnotes and .caltrash directory

### ISSUE THREAD

**Issue by thenktor** [dubyte/dir2opds#19]
Hi,

I did a test run using the `-calibre` argument on my Calibre library (version 7.12 on macOS) and I'm seeing those two directories listed: `.calnotes` and `.caltrash`. I guess those should actually be hidden.

**Comment by dubyte** [comment]
Thanks I will update the calibre option with this files.

**Comment by dubyte** [comment]
This has been implemented
