### ISSUE TITLE
Feature request: Option to hide all files starting with '.'

### ISSUE THREAD

**Issue by thenktor** [dubyte/dir2opds#21]
Hi,

it would be nice if all files starting with `.`could be hidden, because these are hidden files on unix-like systems. A very popular example are `.DS_Store` files, that macOS insists to write to directories.

Thanks

P.S. this also relates to issue #19

**Comment by dubyte** [comment]
Sounds a grate idea, let me add this.

**Comment by dubyte** [comment]
This has been implemented.
