### ISSUE TITLE
Provide init scripts/files

### ISSUE THREAD

**Issue by thenktor** [dubyte/dir2opds#26]
Hi,

if interested I can create init scripts/files for:
* systemd (various Linux distributions)
* OpenRC (Alpine Linux and others)
* FreeBSD
* SMF (illumos/OpenSolaris distributions, e.g. OmniOS)

Please let me know, then I'll create a PR.

**Comment by dubyte** [comment]
Thanks, sounds good, if you want, that would be nice.

**Comment by thenktor** [comment]
I guess I can do this next week...

**Comment by dubyte** [comment]
After merge the PR this issue is resolver thank @thenktor
