### ISSUE TITLE
limited test results on iOS

### ISSUE THREAD

**Issue by kulak** [dubyte/dir2opds#30]
### Cantook

It works on Cantook reader for me on iPhone.

<https://apps.apple.com/us/app/cantook-by-aldiko/id1476410111>

It would be nice if this was stated in README.

### KYBook 3

It works with [KyBook 3 Ebook Reader](https://apps.apple.com/us/app/kybook-3-ebook-reader/id1348198785) if access to Local Network is enabled in settings.  

To enable access go to Settings -> Apps -> KyBook 3 -> Local Network (checked).

It seems that KyBook is so old, that it does not trigger access prompt from iOS, so it has to be configured manually.

**Comment by dubyte** [comment]
Hello @kulak thanks for this. Please correct me if I am wrong: you want to add a section in the readme about tested apps. 
So it should be ok if I put what you have here on the Readme right?
if that is the case I would be happy to add your contribution. If is something else please explain me.

Thanks

**Comment by kulak** [comment]
Yes, that was my thought.

It would be nice to update README.   This way people can get an idea that application is sufficiently standards compliant  to work with OPDS clients.

You are the owner, so it is up to you.
