### ISSUE TITLE
Moon+ Reader v5.2.8 (latest as of 2020-05) fails to download meta data and files

### ISSUE THREAD

**Issue by clach04** [dubyte/dir2opds#4]
See https://github.com/clach04/dir2opds/wiki/Tested-Clients

I followed the readme and had 2 directories and then in each directories only files:

  * epub
      * file.epub
  * cbz
      * file.cbz

but Moon+Reader fails to download anything after the directory metadata. This is is due to Moon+Reader expecting full path, e.g.:

    diff --git a/main.go b/main.go
    index 1e0a0e3..c661de3 100644
    --- a/main.go
    +++ b/main.go
    @@ -160,7 +160,7 @@ func getType(name string, pathType int) string {
     }

     func getHref(req *http.Request, name string) string {
    -       return strings.Replace(
    +       return "http://192.168.1.2:8080" + strings.Replace(  // Fully qualify test
     hack for Moon+ Reader
             filepath.Join(req.URL.EscapedPath(), url.PathEscape(name)),
             "\\", "/", -1)  // Windows path conversion - NOOP on non-Windows
     }

NOTE patch against https://github.com/clach04/dir2opds/tree/comic branch

**Comment by dubyte** [comment]
could you confirm if this still happening after the changes in: https://github.com/dubyte/dir2opds/tree/release_0_4_0

**Comment by dubyte** [comment]
the server doesn't need the full path because with the server is not given it is implicit that it is in the same server the download issue was because I was urlscaping it when it is not really needed.

It should be fixed in v0.0.4 

btw do you know that you can do cross-compiling?
https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04

the trick is to update GOOS and GOARCH env variables.

**Comment by clach04** [comment]
thanks @dubyte I just learned about cross compiling, and I was able to install a current golang version :-) I need to do some more testing now when I get a few hours free :)

**Comment by clach04** [comment]
Managed to get time to build you headrevs on master with Raspberry Pi:
* Raspbian GNU/Linux 9 (stretch)
* go version go1.13.11 linux/arm

Worked great! Not had chance to try with Moon+ but based on inspection of xml in web browser - looks good :+1:  :)

**Comment by clach04** [comment]
Also able to get this running on a Rock64 using a binary built under Raspbian. :)

I was not able to build in-place (distro I run live only had `gccgo-go`, which reports as `go version go1.6.1 gccgo (Debian 6.3.0-18+deb9u1) 6.3.0 20170516 linux/arm`

**Comment by dubyte** [comment]
Nice

**Comment by clach04** [comment]
Confirmed Moon+ Reader is working with version in master and includes full path (sans protocol). :)

**Comment by dubyte** [comment]
Nice thanks
