### ISSUE TITLE
Comic support

### ISSUE THREAD

**Issue by clach04** [dubyte/dir2opds#5]
See https://github.com/clach04/dir2opds/wiki/Tested-Clients for working comic CBZ/CBR support :)

**Comment by clach04** [comment]
TODO see if multiple mime types can be provided in XML, see http://fileformats.archiveteam.org/wiki/Comic_Book_Archive

**Comment by dubyte** [comment]
I am adding the mime types you suggested
https://github.com/dubyte/dir2opds/tree/release_0_4_0

**Comment by dubyte** [comment]
I added the support of the comic base on your work. It is in v0.0.4
