### ISSUE TITLE
dir2opds on Microsoft Windows generates incorrect path (slashes/directory separator)

### ISSUE THREAD

**Issue by clach04** [dubyte/dir2opds#7]
When running dir2opds under Microsoft Windows the wrong directory separator is used, `\` versus `/`. Example:

    <feed>
    <title>Catalog in /cbz</title>
    <id>/cbz</id>
    <link rel="start" href="/" type="application/atom+xml;profile=opds-catalog;kind=navigation"/>
    <updated>2020-05-25T09:20:39-07:00</updated>
    <author>
    <name/>
    </author>
    <entry>
    <title>Elf Receiver Radio-Craft August 1936.cbz</title>
    <id>/cbzElf Receiver Radio-Craft August 1936.cbz</id>
    <link rel="http://opds-spec.org/acquisition" href="\cbz\Elf%20Receiver%20Radio-Craft%20August%201936.cbz" type="application/x-cbz" title="Elf Receiver Radio-Craft August 1936.cbz"/>
    <published>2020-05-25T09:20:39-07:00</published>
    <updated>2020-05-25T09:20:39-07:00</updated>
    </entry>
    </feed> 

quick hack to address this is in issue #4 via (probably dumb) string search/replace (I don't know Go well enough to know the best way to handle this).

**Comment by clach04** [comment]
hack that works for me https://github.com/clach04/dir2opds/commit/2768fd1a75a11519d2a38d989edceef51d70c51c

**Comment by dubyte** [comment]
Ahh I see, thanks, I will check that.

**Comment by dubyte** [comment]
I think instead of filepath.join this should be using: https://golang.org/pkg/path/#Join

That should fix the problem in windows and Linux, I will test later.

**Comment by dubyte** [comment]
Hello, @clach04 I think I fix this in the last release, could you confirm? 
Thanks
